### ISSUE TITLE
Add Ivy

### ISSUE THREAD

**Issue by tisnik** [codereport/array-language-comparisons#5]
It might be probably interesting to add K language into the comparison table. It's a bit tricky as there are various K language "versions", but at least one very nice open sourced implementation exists:
https://github.com/kevinlawler/kona/wiki

Also Ivy is interesting language (or rather "desk calculator on steroids"). It supports rational numbers etc.
https://pkg.go.dev/robpike.io/ivy

-----
To Do: 
* [x] Add Ivy
* [ ] Add K6

**Comment by codereport** [comment]
I agree that K should be added, but what version? It feels odd added an "abandoned" language. And there are multiple open source Ks to choose from: https://k.miraheze.org/wiki/Running_K#Table_of_Implementations

Kona is K3
oK is K6
ngn/k is K6

**Comment by tisnik** [comment]
That's true @codereport . To be honest I'm not super familiar with K (just played with Kona for some time + wrote article about it), but at least K3/K6 seems to have very similar basic properties. I'll check it.

**Comment by tisnik** [comment]
(btw I heard your comments about this issue on Arraycast - very nice work!)

**Comment by codereport** [comment]
Won't be adding K.
